###Test Case #1
POST http://localhost:8000/api/order
Content-Type: application/json

[
{"id":1},
{"id":2},
{"id":3},
{"id":1},
{"id":2}
]

###Test Case #2
POST http://localhost:8000/api/order
Content-Type: application/json

[
{"id":3},
{"id":3},
{"id":2}
]

###Test Case #3
POST http://localhost:8000/api/order
Content-Type: application/json

[
{"id":1},
{"id":1},
{"id":3}
]